CREATE TABLE clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID,
    company_name VARCHAR(255) NOT NULL,
    cnpj VARCHAR(20) UNIQUE,
    company_type VARCHAR(100),
    main_activity TEXT,
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    legal_representative_name VARCHAR(255),
    legal_representative_cpf VARCHAR(15),
    legal_representative_email VARCHAR(255),
    legal_representative_phone VARCHAR(50),
    status VARCHAR(50) DEFAULT 'lead' CHECK (status IN ('lead',
    'active',
    'inactive',
    'prospect')),
    lead_source VARCHAR(100),
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);