CREATE TABLE contracts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    proposal_id UUID NOT NULL,
    client_id UUID NOT NULL,
    contract_number VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending',
    'sent_for_signature',
    'signed',
    'active',
    'terminated',
    'cancelled')),
    contract_type VARCHAR(100),
    start_date DATE,
    end_date DATE,
    auto_renewal BOOLEAN DEFAULT false,
    signed_date TIMESTAMP WITH TIME ZONE,
    contract_file_url TEXT,
    signed_contract_url TEXT,
    monthly_value DECIMAL(12,2),
    annual_value DECIMAL(12,2),
    payment_day INTEGER,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);